apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestaopedidos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestaopedidos
  template:
    metadata:
      labels:
        app: gestaopedidos
    spec:
      containers:
        - name: gestaopedidos
          image: 452371883837.dkr.ecr.us-east-1.amazonaws.com/tech_challenge_repository:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: terraform-20241218025751363800000001.crusf4kyur0s.452371883837.rds.amazonaws.com
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: gestaopedidos
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: Secret123456
            - name: ML_ACCESS_TOKEN
              value: APP_USR-4103898864629348-100313-818c0e2802debe0ad24344fa2b6bcc46-2016994601
            - name: ML_USER_ID
              value: "2016994601"
            - name: ML_EXTERNAL_POS_ID
              value: caixa1
            - name: APP_URL
              value: https://ngbczhmwee.execute-api.us-east-1.amazonaws.com/gestaopedidos
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
